version: 2

x-common: &common
  directory: /
  schedule:
    interval: daily
  assignees:
    - aszili

updates:
  - package-ecosystem: github-actions
    <<: *common

  - package-ecosystem: docker
    <<: *common
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: npm
    <<: *common