name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main      
  workflow_dispatch:
    inputs:
      force:
        description: Build the image even if it already exists
        required: false
        default: false
        type: boolean

jobs:
  initialize:
    runs-on: ubuntu-latest

    outputs:
      TARGET_IMAGE_TAG: ${{ steps.flatnotes_version.outputs.version }}
      FLATNOTES_VERSION: ${{ steps.prepare.outputs.flatnotes_version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read Flatnotes version from package.json
        id: flatnotes_version
        run: |
          VERSION=$(jq -r '.dependencies.flatnotes' package.json | cut -d'#' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare version (remove leading v)
        id: prepare
        run: |
          VERSION="${{ steps.flatnotes_version.outputs.version }}"
          echo "flatnotes_version=${VERSION#v}" >> $GITHUB_OUTPUT

  build:
    needs: initialize
    uses: aszili/github-actions/.github/workflows/build-docker-image.yml@main
    with:
      target_tag: ${{ needs.initialize.outputs.TARGET_IMAGE_TAG }}
      build_args: FLATNOTES_VERSION=${{ needs.initialize.outputs.FLATNOTES_VERSION }}
      force: ${{ contains(inputs.force, 'true') }}
